<a href="https://colab.research.google.com/github/Anush-Amin/Data-Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.80352671, 0.15712503, 0.53235514, 0.48276092, 0.07919432])

In [19]:
np.random.rand(5, 5)

array([[0.12144373, 0.63413538, 0.81692779, 0.9752072 , 0.49002666],
       [0.17328268, 0.81566077, 0.88264503, 0.21085592, 0.90617366],
       [0.33387575, 0.61237348, 0.94261772, 0.17292979, 0.46587293],
       [0.38637621, 0.79167093, 0.81264221, 0.83165307, 0.66862415],
       [0.85472719, 0.58754301, 0.79220118, 0.16879651, 0.82951468]])

In [21]:
np.random.randn(4, 4)

array([[ 0.17728534,  0.37355843,  0.20833574,  0.36000748],
       [-0.25231368,  0.33906967, -1.26595008, -0.9265754 ],
       [ 1.09976488,  0.14455794, -1.72791065,  1.40466302],
       [-0.55380051, -1.69797921,  1.50672477, -1.17263027]])

In [23]:
np.random.randint(1, 100, 10)

array([12, 84, 19, 92, 37,  1, 50, 42, 41, 50])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0, 50, 10)

In [27]:
ranarr

array([38, 29,  0, 27, 42, 19, 29,  3, 27, 15])

In [28]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

42

In [30]:
ranarr.min()

0

In [31]:
ranarr.argmax()

4

In [32]:
ranarr.argmin()

2

In [34]:
arr.shape

(25,)

In [37]:
arr = arr.reshape(5, 5)

In [38]:
arr.shape

(5, 5)

In [39]:
arr.dtype

dtype('int64')

**NumPy Indexing and Selection**

In [41]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[8]

8

In [44]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d[0][0]

5

In [50]:
arr_2d[1, 2]

30

In [53]:
arr_2d[:, :2] = 100

In [54]:
arr_2d

array([[100, 100,  15],
       [100, 100,  30],
       [100, 100,  45]])

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [59]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [60]:
arr[arr<3]

array([0, 1, 2])

In [61]:
arr_2d = np.arange(50).reshape(5, 10)

In [64]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**Numpy Operations**


*   Array with Array
*   Array with Scalars
*   Universal Array Functions





In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [68]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [70]:
arr / arr

<ipython-input-70-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])